# Lession 1

In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer

C:\Users\shubham\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
sentence=[
    'i love dog',
    'I, love my cat',
    'what do i think ?'
]

In [41]:
t=Tokenizer(num_words=100,oov_token="<OOV>")
t.fit_on_texts(sentence)
word_index=t.word_index
print(word_index)

{'<OOV>': 1, 'i': 2, 'love': 3, 'dog': 4, 'my': 5, 'cat': 6, 'what': 7, 'do': 8, 'think': 9}


In [42]:
sequence=t.texts_to_sequences(sentence)
print(sequence)

[[2, 3, 4], [2, 3, 5, 6], [7, 8, 2, 9]]


In [43]:
test_data=[
    'they love dog'
]

In [44]:
test_seq=t.texts_to_sequences(test_data)
print("test sequence",test_seq)

test sequence [[1, 3, 4]]


In [7]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [9]:
padded=pad_sequences(sequence)
print(padded)

[[0 2 3 4]
 [2 3 5 6]
 [7 8 2 9]]


In [10]:
padded_after=pad_sequences(sequence,padding='post')
print(padded_after)

[[2 3 4 0]
 [2 3 5 6]
 [7 8 2 9]]


In [11]:
padded_max=pad_sequences(sequence,padding='post',truncating='post',maxlen=3)
print(padded_max)

[[2 3 4]
 [2 3 5]
 [7 8 2]]


# link to download dataset https://www.kaggle.com/rmisra/news-headlines-dataset-for-sarcasm-detection

In [12]:
import json

In [25]:
with open("sarcasm.json","r") as f:
    datastore=json.load(f)

In [27]:
sentences=[]
labels=[]
url=[]
for item in datastore:
    sentences.append(item["headline"])
    labels.append(item["is_sarcastic"])
    url.append(item["article_link"])

In [29]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [31]:
tokenizer=Tokenizer(oov_token="<OOV>")

In [32]:
tokenizer.fit_on_texts(sentences)
word_index=tokenizer.word_index

In [34]:
sequences=tokenizer.texts_to_sequences(sentences)
padded=pad_sequences(sequences,padding="post")

In [35]:
print(padded[0])

[ 5 11 12  2 13 14 15 16  6 17 18 19  7 20 21 22 23]


In [36]:
print(padded.shape)

(11, 17)
